In [1]:
import polars as pl
import numpy as np
import altair as alt
alt.data_transformers.enable("vegafusion")
WINDOW_SIZE = 32

In [4]:
not 45

False

In [2]:
df_train = pl.read_parquet('../data/processed/standard_10k_32_test_train.parquet')
df_test = pl.read_parquet('../data/processed/standard_10k_32_test_test.parquet')
len(df_train)/(len(df_test)+len(df_train))

FileNotFoundError: No such file or directory (os error 2): ../data/processed/standard_10k_32_test_train.parquet

This error occurred with the following context stack:
	[1] 'parquet scan'
	[2] 'sink'


In [5]:
df_train = pl.read_parquet('../data/processed/standard_all_32_train.parquet')
# df_test = pl.read_parquet('../data/processed/standard_all_32_test.parquet')
len(df_train)/(len(df_test)+len(df_train))

: 

In [3]:
df_train['label'].mean(), df_test['label'].mean()

(0.5011783294006328, 0.5069963935528348)

In [4]:
df_train.head()

shape: (5, 8)
┌─────────────┬────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬───────┐
│ read_name   ┆ cg_pos ┆ seq         ┆ fi          ┆ fp          ┆ ri         ┆ rp         ┆ label │
│ ---         ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---        ┆ ---        ┆ ---   │
│ str         ┆ i64    ┆ str         ┆ list[u16]   ┆ list[u16]   ┆ list[u16]  ┆ list[u16]  ┆ i32   │
╞═════════════╪════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪═══════╡
│ m64168_2008 ┆ 1984   ┆ GAGCCGGGGTT ┆ [21, 27, …  ┆ [14, 21, …  ┆ [18, 33, … ┆ [19, 14, … ┆ 1     │
│ 23_191315/2 ┆        ┆ TCACCGCGTTA ┆ 14]         ┆ 46]         ┆ 40]        ┆ 31]        ┆       │
│ 231102/c…   ┆        ┆ GCCAGGAT…   ┆             ┆             ┆            ┆            ┆       │
│ m64168_2008 ┆ 6481   ┆ TATCTAAATGA ┆ [14, 20, …  ┆ [27, 22, …  ┆ [33, 22, … ┆ [38, 12, … ┆ 0     │
│ 20_000733/2 ┆        ┆ AGTACGTATTT ┆ 38]         ┆ 22]         ┆ 17]        ┆ 14]        ┆       │
│ 62810/cc…   ┆        ┆ ATACAAGT…   ┆             ┆             ┆            ┆            ┆       │
│ m64168_2008 ┆ 7092   ┆ TAACATGCTAT ┆ [27, 37, …  ┆ [37, 23, …  ┆ [25, 27, … ┆ [15, 8, …  ┆ 1     │
│ 23_191315/1 ┆        ┆ AACACGCTGCA ┆ 20]         ┆ 33]         ┆ 10]        ┆ 11]        ┆       │
│ 180098/c…   ┆        ┆ CATGCAAC…   ┆             ┆             ┆            ┆            ┆       │
│ m64168_2008 ┆ 6056   ┆ AGGATCACTTG ┆ [34, 23, …  ┆ [20, 23, …  ┆ [76, 24, … ┆ [33, 18, … ┆ 0     │
│ 20_000733/4 ┆        ┆ AGCTCGGGAAG ┆ 28]         ┆ 30]         ┆ 21]        ┆ 11]        ┆       │
│ 61584/cc…   ┆        ┆ CAGAGGCT…   ┆             ┆             ┆            ┆            ┆       │
│ m64168_2008 ┆ 1103   ┆ TGCAGCACTAG ┆ [34, 23, …  ┆ [10, 18, …  ┆ [28, 20, … ┆ [18, 7, …  ┆ 0     │
│ 20_000733/3 ┆        ┆ CAGACGCGCCA ┆ 11]         ┆ 41]         ┆ 17]        ┆ 8]         ┆       │
│ 30109/cc…   ┆        ┆ TGTGTGTT…   ┆             ┆             ┆            ┆            ┆       │
└─────────────┴────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴───────┘

In [6]:
df_train['fi'].to_numpy()

array([array([52, 29, 39, 35, 20, 23,  6, 23, 34, 40, 38, 35, 18, 69, 22, 35, 21,
              22, 18, 15, 29, 22, 27, 66, 62, 45, 23, 37, 11,  9,  8, 21])       ,
       array([ 19,  60,  29,  50,  45,  29,  35,  14,  14,  59,  39,  20,  81,
               56,  33,  52,  21,  22,  50,  23, 126,  70,  63,  25, 145,  43,
               55,  20,  48,  26,  24,  39])                                  ,
       array([ 23,  59,  14,  21,  47,  27,  51,  13,  16,  69,  31,   9,  18,
               20,  45,  84,  61, 131, 163,  31,  34,  34,  70,  47,  29,  29,
               39,  32,  10,  24,  70,  69])                                  ,
       ...,
       array([11, 28, 12, 19,  9, 14, 19, 13, 21, 21, 14, 15, 24, 15, 22, 20, 30,
              16, 18, 19, 13, 12, 24, 20, 21, 23, 11, 13, 12, 19, 67, 16])       ,
       array([16, 25, 22, 13, 17, 13, 14,  8, 14, 13, 27,  9, 14, 15, 15, 13, 35,
              18, 11, 15, 11, 17, 22, 14, 15, 23, 11, 14, 14, 14, 12, 14])       ,
       array([ 26

In [ ]:
kinetic_cols = ['fi', 'fp', 'ri', 'rp']
data_array = np.stack([df_train.slice(0,1)[c].to_numpy() for c in kinetic_cols], axis=1)
data_array.shape

(1, 4)

In [ ]:
lengths = df_train["fi"].list.len()
all_equal = lengths.n_unique() == 1
print(all_equal)

True


In [ ]:
df_train = pl.read_parquet('../data/processed/train_cg_32_10000.parquet')
df_train = df_train.with_columns([
    # pl.col("seq").list.to_array(WINDOW_SIZE),  
    pl.col("fi").list.to_array(WINDOW_SIZE),  
    pl.col("fp").list.to_array(WINDOW_SIZE), 
    pl.col("ri").list.to_array(WINDOW_SIZE), 
    pl.col("rp").list.to_array(WINDOW_SIZE), 
    ])


In [ ]:

arr = np.stack([df_train[col].to_numpy() for col in kinetic_cols], axis=1)
arr.shape

(1361342, 4, 32)

In [ ]:
unique_chars = (
    df_train.select(
        pl.col("seq").str.explode().unique().alias("unique_chars")
    )
)
unique_chars

/var/folders/wt/33m104j54lb3xnbgck84qsw40000gp/T/ipykernel_1306/1930145770.py:3: DeprecationWarning: `str.explode` is deprecated; use `str.split("").explode()` instead. Note that empty strings will result in null instead of being preserved. To get the exact same behavior, split first and then use a `pl.when...then...otherwise` expression to handle the empty list before exploding.
  pl.col("seq").str.explode().unique().alias("unique_chars")


shape: (4, 1)
┌──────────────┐
│ unique_chars │
│ ---          │
│ str          │
╞══════════════╡
│ C            │
│ T            │
│ A            │
│ G            │
└──────────────┘

In [ ]:
vocab = {'A':0, 'T':1, 'C':2, 'G':3}
seq_ints = (
    df_train["seq"]
    .str.split("")                # Split into characters
    .list.eval(                   # Evaluate an expression on each list element
        pl.element().replace_strict(vocab)
    )
    .to_numpy()                   # Convert to NumPy array
)
np.stack(seq_ints).shape

(1361342, 32)

In [ ]:
np.stack([df_train[:5][c].to_numpy() for c in kinetic_cols], axis=1)

array([[array([52, 29, 39, 35, 20, 23,  6, 23, 34, 40, 38, 35, 18, 69, 22, 35, 21,
               22, 18, 15, 29, 22, 27, 66, 62, 45, 23, 37, 11,  9,  8, 21])       ,
        array([19, 10, 31, 16, 26, 12, 13, 23, 21,  9, 19,  8, 26, 17, 16, 22, 19,
               12, 38, 27, 19, 30, 41, 13, 14, 12, 12, 12, 17, 38, 13, 14])       ,
        array([ 62,  14,  26,  15,  71,  30,  30,  19,  12,  18,  24,  23,  36,
               139, 176,  49,  50,  49,  26,  34,  33,  27,  23,  26,  37,  38,
                32,  22,  59,  28,  43,  12])                                  ,
        array([29, 25, 19, 26, 16, 16,  7, 32, 39, 12, 33, 11, 10, 12, 28,  7, 14,
               16, 20, 24, 34, 16, 11, 15, 10, 14, 28, 22, 27, 24, 62, 13])       ],
       [array([ 19,  60,  29,  50,  45,  29,  35,  14,  14,  59,  39,  20,  81,
                56,  33,  52,  21,  22,  50,  23, 126,  70,  63,  25, 145,  43,
                55,  20,  48,  26,  24,  39])                                  ,
        array([1

In [ ]:
list_of_2d_arrays: np.stack([np.array(df_train[c].to_list()) for c in kinetic_cols], axis=1)

In [ ]:
list_of_2d_arrays

[array([[52, 29, 39, ...,  9,  8, 21],
        [19, 60, 29, ..., 26, 24, 39],
        [23, 59, 14, ..., 24, 70, 69],
        ...,
        [11, 28, 12, ..., 19, 67, 16],
        [16, 25, 22, ..., 14, 12, 14],
        [26, 91, 17, ..., 57, 21, 50]], shape=(1361342, 32)),
 array([[19, 10, 31, ..., 38, 13, 14],
        [12, 49, 15, ...,  9, 11, 24],
        [12, 25, 16, ..., 35, 12,  9],
        ...,
        [12, 17, 21, ..., 32, 24, 28],
        [14, 16, 52, ..., 29, 12, 58],
        [22, 39, 17, ..., 25,  7, 22]], shape=(1361342, 32)),
 array([[62, 14, 26, ..., 28, 43, 12],
        [31, 52, 26, ..., 34, 20, 28],
        [35, 48,  5, ..., 31, 65, 68],
        ...,
        [16, 17, 16, ..., 31, 10, 24],
        [17, 13,  6, ..., 17,  9, 19],
        [ 9, 11, 15, ..., 13, 25,  5]], shape=(1361342, 32)),
 array([[29, 25, 19, ..., 24, 62, 13],
        [12, 17, 20, ..., 24, 28, 54],
        [18, 11, 11, ..., 19,  7, 28],
        ...,
        [12, 18, 28, ..., 27, 23, 29],
        [19, 39, 45, 

In [ ]:
df_train = pl.read_parquet('../data/processed/test_run_train.parquet')
df_test = pl.read_parquet('../data/processed/test_run_test.parquet')
len(df_train)/(len(df_test)+len(df_train))

0.7999774431850223

In [ ]:
df_test['label'].mean()

0.4990132506343389

In [ ]:
import re
seq = 'ATCGATCGAA'
cgs = re.finditer('CG', seq)
print(seq)
for match in cgs:
    print(match.start())

ATCGATCGAA
2
6


In [ ]:
df_train_singletons = pl.read_parquet('../data/processed/1k_singletons_train.parquet')
df_test_singletons = pl.read_parquet('../data/processed/1k_singletons_test.parquet')
len(df_train_singletons)


85155

In [1]:
import torch

: 

In [4]:
x = torch.ones((10,20,30))
x.shape
x.permute(2,1,0).shape

torch.Size([30, 20, 10])

In [2]:
import torch

In [1]:
from src.dataset_class import MethylIterableDataset

In [ ]:
train_