In [62]:
import polars as pl
import numpy as np
import altair as alt
alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

In [63]:
df_train = pl.read_parquet('../data/processed/train_cg_32_10000.parquet')
df_test = pl.read_parquet('../data/processed/test_cg_32_10000.parquet')
len(df_train)/(len(df_test)+len(df_train))

0.7999994129526136

In [64]:
df_train['label'].mean(), df_test['label'].mean()

(0.5025958520668853, 0.5025962094461518)

In [65]:
df_train.head()

shape: (5, 8)
┌─────────────┬────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬───────┐
│ read_name   ┆ cg_pos ┆ window_seq  ┆ window_fi   ┆ window_fp   ┆ window_ri  ┆ window_rp  ┆ label │
│ ---         ┆ ---    ┆ ---         ┆ ---         ┆ ---         ┆ ---        ┆ ---        ┆ ---   │
│ str         ┆ i64    ┆ str         ┆ list[i64]   ┆ list[i64]   ┆ list[i64]  ┆ list[i64]  ┆ i32   │
╞═════════════╪════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪═══════╡
│ m64168_2008 ┆ 6281   ┆ GGGCATGGTGG ┆ [14, 14, …  ┆ [21, 20, …  ┆ [37, 47, … ┆ [17, 38, … ┆ 0     │
│ 20_000733/5 ┆        ┆ CGGGCGCCTGT ┆ 15]         ┆ 10]         ┆ 14]        ┆ 25]        ┆       │
│ 90611/cc…   ┆        ┆ AGTCCCAG…   ┆             ┆             ┆            ┆            ┆       │
│ m64168_2008 ┆ 5478   ┆ TAGGAAGACCT ┆ [10, 20, …  ┆ [28, 12, …  ┆ [16, 36, … ┆ [15, 30, … ┆ 0     │
│ 20_000733/6 ┆        ┆ TGCCCGGGATG ┆ 18]         ┆ 55]         ┆ 29]        ┆ 19]        ┆       │
│ 56442/cc…   ┆        ┆ GTTCAGGG…   ┆             ┆             ┆            ┆            ┆       │
│ m64168_2008 ┆ 1125   ┆ CTGAGGGCTCC ┆ [7, 20, …   ┆ [11, 21, …  ┆ [21, 54, … ┆ [28, 23, … ┆ 0     │
│ 20_000733/3 ┆        ┆ AGCTCGTACGC ┆ 30]         ┆ 37]         ┆ 20]        ┆ 28]        ┆       │
│ 95276/cc…   ┆        ┆ AGCAGGAC…   ┆             ┆             ┆            ┆            ┆       │
│ m64168_2008 ┆ 1138   ┆ AAACGGGTAGC ┆ [32, 35, …  ┆ [10, 15, …  ┆ [109, 118, ┆ [43, 22, … ┆ 0     │
│ 20_000733/3 ┆        ┆ ATTACGTCAGG ┆ 74]         ┆ 22]         ┆ … 100]     ┆ 23]        ┆       │
│ 30186/cc…   ┆        ┆ CACAGAAG…   ┆             ┆             ┆            ┆            ┆       │
│ m64168_2008 ┆ 3289   ┆ CCACGGGAGTG ┆ [13, 9, …   ┆ [69, 23, …  ┆ [29, 21, … ┆ [24, 24, … ┆ 1     │
│ 23_191315/9 ┆        ┆ TGGACGAGGAG ┆ 15]         ┆ 36]         ┆ 18]        ┆ 20]        ┆       │
│ 17719/cc…   ┆        ┆ CTGAGCAA…   ┆             ┆             ┆            ┆            ┆       │
└─────────────┴────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴───────┘

In [67]:
df_train['window_fi'].to_numpy()

array([array([14, 14, 16, 31, 28, 34, 80, 17, 11, 31, 13, 24, 23, 18, 30, 30, 24,
              25,  8, 14, 15, 14, 17, 52, 48, 34, 30, 31, 44, 21, 16, 15])       ,
       array([ 10,  20,  26,  17,  41,  65,  35,  86,  25,  32,  52,  68,  42,
               17,  14, 106,  31,  26,  20,  20,  18,  28,  22,  13,  24,  30,
               10,  14,  30,  16,  21,  18])                                  ,
       array([ 7, 20, 22, 65, 24, 14, 13, 15, 21, 81, 13, 11, 16, 17, 25, 19, 20,
              17, 77, 33, 24, 26, 33, 34, 80, 26, 25, 36, 40, 29, 50, 30])       ,
       ...,
       array([ 33,  13,  60,  18,  32,  25,  27,   9,  16,  24, 107,  61,  58,
               27,  19,  16,  21,  15,  56,  23,  33,  26, 122,  79,   5,  48,
              100,  13,  80,  21,  36,  21])                                  ,
       array([10, 17, 23, 36,  9, 18,  9, 38, 19, 15, 29, 17, 31, 14, 23, 17, 18,
              12, 11, 16,  3, 15, 27, 15,  7, 38, 35, 14, 59, 11,  8, 33])       ,
       array([ 16